// File generated by FlutterFire CLI.
// PLACEHOLDER - You need to run: flutterfire configure
// This will generate the actual firebase_options.dart file with your Firebase project settings

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCSXwacvzTwe5cvbUfwVcKI1zExzJfkM',
    appId: '1:881289616895:web:3f6794fb26d68397de9bca',
    messagingSenderId: '881289616895',
    projectId: 'doctor-4dfc5',
    authDomain: 'doctor-4dfc5.firebaseapp.com',
    storageBucket: 'doctor-4dfc5.firebasestorage.app',
    measurementId: 'G-HWY7XGZZ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkGNnyFGrL7VtlU5YRW_66IDXc3alTok',
    appId: '1:881289616895:android:f13d2eb9cf8a3727de9bca',
    messagingSenderId: '881289616895',
    projectId: 'doctor-4dfc5',
    storageBucket: 'doctor-4dfc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVNsz8J4zTpmXKQKRCu5CfZNSTlQRaO-U',
    appId: '1:881289616895:ios:9a798afc6a892ddade9bca',
    messagingSenderId: '881289616895',
    projectId: 'doctor-4dfc5',
    storageBucket: 'doctor-4dfc5.firebasestorage.app',
    iosClientId: '881289616895-f7spiomd60mu6ltnhogqiaqo73p1goia.apps.googleusercontent.com',
    iosBundleId: 'com.doctor.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVNsz8J4zTpmXKQKRCu5CfZNSTlQRaO-U',
    appId: '1:881289616895:ios:9a798afc6a892ddade9bca',
    messagingSenderId: '881289616895',
    projectId: 'doctor-4dfc5',
    storageBucket: 'doctor-4dfc5.firebasestorage.app',
    iosClientId: '881289616895-f7spiomd60mu6ltnhogqiaqo73p1goia.apps.googleusercontent.com',
    iosBundleId: 'com.doctor.doctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOCSXwacvzTwe5cvbUfwVcKI1zExzJfkM',
    appId: '1:881289616895:web:3f6794fb26d68397de9bca',
    messagingSenderId: '881289616895',
    projectId: 'doctor-4dfc5',
    authDomain: 'doctor-4dfc5.firebaseapp.com',
    storageBucket: 'doctor-4dfc5.firebasestorage.app',
    measurementId: 'G-HWY7XGZZ3Z',
  );

}